
title: Resume
url: 'http://webjeda.com'
baseurl: ''


#Profile information
name: Brad Bazemore
tagline: Robotics developer that loves web apps
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone:
website: bradbazemore.com #do not add http://
linkedin:
github: sonyccd
twitter: '@bwbaze'

skills:
  - name: ROS
    level: 98%
  - name: Python
    level: 50%



