# You can use emojies now!
# to test set the url to localhost and the base url blank
gems:
  - jemoji

title: Resume
# Use for deploy to github
url: 'https://sonyccd.github.io'
baseurl: '/resume'
# Use for local testing
#url: 'localhost'
#baseurl:  ''

#Profile information
name: Brad Bazemore
tagline: Go web developer with a love for open source and IoT
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone:
# website: bradbazemore.com #do not add http://
linkedin: bradfordbazemore
github: sonyccd

education:
  - degree: "BS in Computer Science"
    school: "Georgia Southern University"
    time: "2010 - 2014"
    
interests: ["caving", "scuba diving", "running", "rock climbing"]

#Content
about: "Independent and self-motivated developer with experience in IoT, Robotics, Big Data and web app development.
        Works well in teams and enjoys a stimulating and challenging work environment."

#For each topic below you can add more than one thing. Each entry is divided by the -. For example each entry in the
#skill is made up of a name and level.

experiences:
  - name: "Co-Founder/Project Director"
    time: "March 2018 - Now"
    company: "Project Hermes"
    description: "We are monitoring the temperatures of the coastal ocean at depth worldwide in near real-time,
     combining satellite surface temperatures and diver measurements, using sensors ranging from precision 
     instruments to dive computer profiles. I am the director of the seven person non-profit organization creating 
     this cloud and IoT solution."

  - name: "Back-End Developer"
    time: "July 2017 - Now"
    company: "Pendo.io"
    description: "I help build out new features for Pendo's Go back end. 
    These can range from simple CRUD to external integrations and time based event management."

  - name: "Developer"
    time: "May 2015 - Jun 2017"
    company: "University of Georgia"
    description: "My work is assisting in the development of the robotic technology required to autonomously
    collect data to monitor crops in a field or orchard."

  - name: "Software Development Intern"
    time: "Jun 2014 - Dec 2014"
    company: "Oak Ridge National Laboratory"
    description: "Worked in the Computational Data Analytic group solving some of the countries most pressing
    problems of cyber security and power reliability."

  - name: "Teaching Assistant"
    time: "May 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Teaching Assistant for the department of Computer Science. This entails grading papers for
    the professors I TA for, supervising labs, and on occasion giving lecture."

  - name: "Undergraduate Research Assistant"
    time: "Jan 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Conducted research in the fields of Cyber Physical Systems, High Performance Computing,
    Robotics, and Operating Systems."

projects:
  - name: "Hermes App"
    description: ":ocean::thermometer: App to monitoring the temperatures of the coastal ocean at depth worldwide in near real-time"
    link: "https://github.com/project-hermes/hermes-app"

  - name: "Hermes Sensor"
    description: ":ocean::thermometer::satellite: Hardware and software for the hermes dive sensor"
    link: "https://github.com/project-hermes/hermes-sensor"

  - name: "Jack-UI"
    description: ":spades: A web based field robot management tool"
    link: "https://github.com/sonyccd/jack-ui"
    
  - name: "Resume"
    description: ":briefcase: A web resume built with Jekyll and hosted on GitHub. (This thing!)"
    link: "https://github.com/sonyccd/resume"

  - name: "Crop Row Follow"
    description: ":corn::video_camera::tractor: ROS node for detecting and following the rows in a row crop"
    link: "https://github.com/sonyccd/crop_row_follow"

  - name: "Black Fish"
    description: ":whale2: Automated malware classification system with spark"
    link: "https://github.com/snakes-in-the-box/blk-fish"

skills:
  - name: Linux
    level: 70%
    
  - name: Go
    level: 80%
   
  - name: Google Cloud (Datastore, App Engine, etc.)
    level: 60%

  - name: Firebase
    level: 75%
    
  - name: Javascript/HTML/CSS
    level: 40%
