
title: Resume
url: 'http://webjeda.com'
baseurl: '' #change it according to your repository name


#Profile information
name: Brad Bazemore
tagline: Robotics developer that loves web apps
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone: 012 345 6789
website: bradbazemore.com #do not add http://
linkedin:
github: sonyccd
twitter: '@bwbaze'

