
title: Resume
url: 'https://sonyccd.github.io'
baseurl: '/resume'


#Profile information
name: Brad Bazemore
tagline: Robotics developer that loves web apps
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone:
website: bradbazemore.com #do not add http://
linkedin: bradfordbazemore
github: sonyccd
twitter: '@bwbaze'

education:
  - degree: "MS in Computer Science"
    school: "University of Georgia"
    time: "2015 - 2018"
    
  - degree: "BS in Computer Science"
    school: "Georgia Southern University"
    time: "2010 - 2014"

#Content
about: ""

#For each topic below you can add more than one thing. Each entry is divided by the -. For example each entry in the
#skill is made up of a name and level.

experiences:
  - name: "Research Assistant"
    time: "May 2015 - Now"
    company: "University of Georgia"
    description: "My work is assisting in the development of the robotic technology required to autonomously
    collect data to monitor crops in a field or orchard."

  - name: "Research Intern"
    time: "Jun 2014 - Dec 2014"
    company: "Oak Ridge National Laboratory"
    description: "Worked in the Computational Data Analytic group solving some of the countries most pressing
    problems of cyber security and power reliability."

  - name: "Teaching Assistant"
    time: "May 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Teaching Assistant for the department of Computer Science. This entails grading papers for
    the professors I TA for, supervising labs, and on occasion giving lecture."

  - name: "Undergraduate Research Assistant"
    time: "Jan 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Conducted research in the fields of Cyber Physical Systems, High Performance Computing,
    Robotics, and Operating Systems."

projects:
  - name: "Jack-UI"
    description: "A web based field robot management tool"
    link: "https://github.com/sonyccd/jack-ui"

skills:
  - name: ROS
    level: 90%
  - name: Python
    level: 85%
  - name: C++
    level: 75%
  - name: Javascript
    level: 75%



