
# to test set the url to localhost and the base url blank
title: Resume
url: 'https://sonyccd.github.io'
baseurl: '/resume'


#Profile information
name: Brad Bazemore
tagline: Robotics and computer vision developer that loves web apps
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: bwbazemore@uga.edu
phone:
website: bradbazemore.com #do not add http://
linkedin: bradfordbazemore
github: sonyccd
twitter: '@bwbaze'

education:
  - degree: "BS in Computer Science"
    school: "Georgia Southern University"
    time: "2010 - 2014"
    
interests: ["caving", "scuba diving", "running"]

#Content
about: "Independent and self-motivated developer with experience in IoT, Robotics, Big Data and web app development.
        Works well in teams and enjoys a stimulating and challenging work environment."

#For each topic below you can add more than one thing. Each entry is divided by the -. For example each entry in the
#skill is made up of a name and level.

experiences:
  - name: "Developer"
    time: "May 2015 - Now"
    company: "University of Georgia"
    description: "My work is assisting in the development of the robotic technology required to autonomously
    collect data to monitor crops in a field or orchard."

  - name: "Software Development Intern"
    time: "Jun 2014 - Dec 2014"
    company: "Oak Ridge National Laboratory"
    description: "Worked in the Computational Data Analytic group solving some of the countries most pressing
    problems of cyber security and power reliability."

  - name: "Teaching Assistant"
    time: "May 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Teaching Assistant for the department of Computer Science. This entails grading papers for
    the professors I TA for, supervising labs, and on occasion giving lecture."

  - name: "Undergraduate Research Assistant"
    time: "Jan 2012 - May 2014"
    company: "Georgia Southern University"
    description: "Conducted research in the fields of Cyber Physical Systems, High Performance Computing,
    Robotics, and Operating Systems."

projects:
  - name: "Jack-UI"
    description: "A web based field robot management tool"
    link: "https://github.com/sonyccd/jack-ui"
    
  - name: "Resume"
    description: "A web resume built with Jekyll and hosted on GitHub. (This thing!)"
    link: "https://github.com/sonyccd/resume"

  - name: "Whitney"
    description: "Counts cotton bolls from images to estimate crop yield"
    link: "https://github.com/sonyccd/whitney"

  - name: "Red Rover Firmware"
    description: "ROS Arduino firmware for Red Rover autonomous tractor"
    link: "https://github.com/sonyccd/red-rover-firmware"

  - name: "Crop Row Follow"
    description: "ROS node for detecting and following the rows in a row crop"
    link: "https://github.com/sonyccd/crop_row_follow"

  - name: "Black Fish"
    description: "Automated malware classification system with spark"
    link: "https://github.com/snakes-in-the-box/blk-fish"

skills:
  - name: ROS
    level: 90%
    
  - name: Python
    level: 85%

  - name: Scikit-Image/OpenCV
    level: 80%

  - name: C/C++
    level: 75%
    
  - name: Javascript/HTML/CSS
    level: 75%
    
  - name: Scala
    level: 60%



