
title: Resume
url: 'https://sonyccd.github.io'
baseurl: '/resume'


#Profile information
name: Brad Bazemore
tagline: Robotics developer that loves web apps
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email:
phone:
website: bradbazemore.com #do not add http://
linkedin:
github: sonyccd
twitter: '@bwbaze'

skills:
  - name: ROS
    level: 90%
  - name: Python
    level: 85%
  - name: C++
    level: 75%
  - name: Javascript
    level: 75%



